#!/bin/bash
# A script to create PreRequisite part 1 by Jayden Aung

# Name of your cluster that will appear on CloudGuard portal. Update this value.
cluster_name="mycluster"

# namespace for CloudGuard (default is checkpoint) 
namespace="checkpoint"

# Your CloudGuard API Key and Secret
CHKP_CLOUDGUARD_API="your-cloudguard-api"
CHKP_CLOUDGUARD_SECRET="your-cloudguard-secret"

dome9ApiUrl="https://api.dome9.com"

# Your Cluster ID which is generated by CloudGuard. 
CREATION_RESPONSE=$(curl -s -X POST $dome9ApiUrl/v2/KubernetesAccount --header 'Content-Type: application/json' --header 'Accept: application/json' \
-d "{\"name\" : \"$cluster_name\"}" --user $CHKP_CLOUDGUARD_API:$CHKP_CLOUDGUARD_SECRET)

export cluster_id=$(echo $CREATION_RESPONSE | jq -r '.id')


# Create your name space
oc create namespace $myns

# Generate secret
oc create secret generic dome9-creds \
--from-literal=username=$CHKP_CLOUDGUARD_API \
--from-literal=secret=$CHKP_CLOUDGUARD_SECRET \
--namespace $myns

# Create Configmap

oc create configmap cp-resource-management-configmap \
--from-literal=cluster.id=,$cluster_id --namespace $myns

# Create Services account
oc create serviceaccount cp-resource-management --namespace $myns

echo Service Account "${myns}" has been created. 

